import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import {
  isGenerated,
  resetGeneratedCache,
} from '../../../../src/core/project/is-generated.js'
import { createTestTmpDir } from '../../../helpers/tmpdir.js'

describe('isGenerated', () => {
  let tmp: string

  beforeEach(() => {
    tmp = createTestTmpDir('is-generated')
    resetGeneratedCache()
  })

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true })
    resetGeneratedCache()
  })

  // header detection
  describe('header detection', () => {
    it('returns false for a file with no generated markers', async () => {
      const p = join(tmp, 'normal.ts')
      writeFileSync(p, '// plain source file\nexport const x = 1\n')
      expect(await isGenerated(p)).toBe(false)
    })

    it('detects @generated in the header', async () => {
      const p = join(tmp, 'generated1.ts')
      writeFileSync(p, '// @generated\nexport {}\n')
      expect(await isGenerated(p)).toBe(true)
    })

    it('detects AUTO-GENERATED (uppercase) case-insensitively', async () => {
      const p = join(tmp, 'generated2.ts')
      writeFileSync(p, '/* AUTO-GENERATED FILE */\nexport {}\n')
      expect(await isGenerated(p)).toBe(true)
    })

    it('detects DO NOT EDIT case-insensitively', async () => {
      const p = join(tmp, 'generated3.ts')
      writeFileSync(p, '// DO NOT EDIT generated by codegen\nexport {}\n')
      expect(await isGenerated(p)).toBe(true)
    })

    it('detects lowercase do not edit', async () => {
      const p = join(tmp, 'generated4.ts')
      writeFileSync(p, '// do not edit\nexport {}\n')
      expect(await isGenerated(p)).toBe(true)
    })

    it('returns false when marker appears after byte 300', async () => {
      const p = join(tmp, 'far.ts')
      const filler = ' '.repeat(300)
      writeFileSync(p, `${filler}@generated`)
      expect(await isGenerated(p)).toBe(false)
    })

    it('returns false for a non-existent file (no crash)', async () => {
      const p = join(tmp, 'does-not-exist.ts')
      expect(await isGenerated(p)).toBe(false)
    })
  })

  // gitignore matching
  describe('gitignore matching', () => {
    it('returns true for a path matched by a directory gitignore pattern', async () => {
      writeFileSync(join(tmp, '.gitignore'), 'dist/\nnode_modules\n.anvil/\n')
      const p = join(tmp, '.anvil', 'registry.json')
      mkdirSync(join(tmp, '.anvil'), { recursive: true })
      writeFileSync(p, '{}')
      expect(await isGenerated(p, tmp)).toBe(true)
    })

    it('returns false for a path not matched by gitignore', async () => {
      writeFileSync(join(tmp, '.gitignore'), 'dist/\n')
      const p = join(tmp, 'src', 'index.ts')
      mkdirSync(join(tmp, 'src'), { recursive: true })
      writeFileSync(p, 'export const x = 1\n')
      expect(await isGenerated(p, tmp)).toBe(false)
    })

    it('matches floating pattern (node_modules)', async () => {
      writeFileSync(join(tmp, '.gitignore'), 'node_modules\n')
      const p = join(tmp, 'node_modules', 'some-pkg', 'index.js')
      mkdirSync(join(tmp, 'node_modules', 'some-pkg'), { recursive: true })
      writeFileSync(p, 'module.exports = {}\n')
      expect(await isGenerated(p, tmp)).toBe(true)
    })

    it('returns false when no .gitignore file exists', async () => {
      const p = join(tmp, 'src', 'index.ts')
      mkdirSync(join(tmp, 'src'), { recursive: true })
      writeFileSync(p, 'export const x = 1\n')
      expect(await isGenerated(p, tmp)).toBe(false)
    })

    it('skips files outside the project root', async () => {
      writeFileSync(join(tmp, '.gitignore'), '*\n')
      const outsidePath = join(tmpdir(), 'anvil-outside-test.ts')
      writeFileSync(outsidePath, 'export const x = 1\n')
      try {
        expect(await isGenerated(outsidePath, tmp)).toBe(false)
      } finally {
        rmSync(outsidePath, { force: true })
      }
    })
  })

  // cache behaviour
  describe('cache', () => {
    it('returns cached result on second call (cache hit)', async () => {
      const p = join(tmp, 'cached.ts')
      writeFileSync(p, '// @generated\nexport {}\n')
      const first = await isGenerated(p)
      // Overwrite so header check would differ if re-read
      writeFileSync(p, '// plain\nexport {}\n')
      const second = await isGenerated(p)
      expect(first).toBe(true)
      expect(second).toBe(true) // still true because cached
    })

    it('resetGeneratedCache() clears the cache so fresh read occurs', async () => {
      const p = join(tmp, 'reset.ts')
      writeFileSync(p, '// @generated\nexport {}\n')
      const first = await isGenerated(p)
      expect(first).toBe(true)
      writeFileSync(p, '// plain\nexport {}\n')
      resetGeneratedCache()
      const second = await isGenerated(p)
      expect(second).toBe(false) // fresh read after cache reset
    })
  })

  // opt-out when no projectRoot
  describe('opt-out (no projectRoot)', () => {
    it('skips gitignore check when projectRoot is not provided', async () => {
      writeFileSync(join(tmp, '.gitignore'), '.anvil/\n')
      const p = join(tmp, '.anvil', 'registry.json')
      mkdirSync(join(tmp, '.anvil'), { recursive: true })
      writeFileSync(p, '{}')
      // Without projectRoot, gitignore is not consulted
      expect(await isGenerated(p)).toBe(false)
    })
  })
})
