/**
 * Canonical 12-intent table for v0.2.0.
 *
 * Pure data — no I/O, no side effects, no non-core imports beyond types.
 * Consumed by `src/intent/router.ts` and the legacy `user-prompt-submit.ts`
 * handler's detection code path (which in v2 delegates to router).
 *
 * Adding / removing / renaming an intent is a breaking change; keep the key
 * in lockstep with the `RoutingDecision.intent` values tests assert on.
 */

export type IntentName =
  | 'autonomous'
  | 'explore'
  | 'review'
  | 'debug'
  | 'plan'
  | 'research'
  | 'test'
  | 'mcp'
  | 'document'
  | 'refactor'
  | 'review-respond'
  | 'install'

export interface IntentKeyword {
  keyword: string | RegExp
  weight: number
}

export interface IntentDefinition {
  name: IntentName
  /** Weighted keyword matchers used by detectIntents. */
  patterns: IntentKeyword[]
  /**
   * Weighted negative matchers. If any match, the intent's score has that
   * weight subtracted. A score ≤ 0 after subtraction vetoes the intent. Used
   * to suppress false positives (e.g., "not a bug", "don't refactor").
   */
  negativePatterns?: IntentKeyword[]
  /** Primary agent the router hands this intent to. */
  defaultAgent: string
  /** Pre-ranked skill bundle the agent receives. Order matters (top first). */
  defaultSkills: string[]
  /**
   * Human-readable phrase summarising the top trigger keywords for this
   * intent. Written into the routing-rules prose (`.claude/rules/anvil-routing.md`
   * and `AGENTS.md`). Generated by `scripts/generate-routing-rules.ts` —
   * single source of truth so prose and metadata cannot drift.
   *
   * Format: top keywords separated by ` / ` (e.g. "review / audit / quality").
   * Keep short — this appears verbatim in the rendered routing doc.
   */
  phrase: string
  /**
   * Prompt-category rules — reasoning / framing rules that shape how the
   * agent should think. Mapped to `RoutingDecision.rules.prompt`.
   */
  applicableRules: string[]
  /**
   * Execution-category rules — rules about the act of doing (verify before
   * claiming done, delegate to the named agent first). Mapped to
   * `RoutingDecision.rules.execution`.
   */
  executionRules?: string[]
  /**
   * Safety-category rules — rules that protect against destructive or
   * irreversible actions. Mapped to `RoutingDecision.rules.safety`.
   */
  safetyRules?: string[]
  /**
   * Workflow-category rules — rules about the order and shape of steps
   * (red → green → refactor, plan → execute → verify). Mapped to
   * `RoutingDecision.rules.workflow`.
   */
  workflowRules?: string[]
}

export const INTENT_DEFINITIONS: Record<IntentName, IntentDefinition> = {
  autonomous: {
    name: 'autonomous',
    phrase: 'ultra / autonomous / just do it / end to end',
    patterns: [
      { keyword: /\bultra\b/, weight: 3 },
      { keyword: /\bautonomous\b/, weight: 3 },
      { keyword: /\bjust do it\b/, weight: 2 },
      { keyword: /\bfully handle\b/, weight: 2 },
      { keyword: /\bend to end\b/, weight: 2 },
      { keyword: /\btake care of\b/, weight: 2 },
      { keyword: /\ball the way\b/, weight: 2 },
      // Plan 31 A2 — stickiness keyword patterns
      { keyword: /\b(polish|ship|tighten|tweak)\b/, weight: 1 },
      { keyword: /\b(make|do) (it|this) better\b/, weight: 2 },
      { keyword: /\bcreate (a|an|the) (new )?(api )?endpoint\b/, weight: 2 },
    ],
    defaultAgent: 'ultra-worker',
    defaultSkills: ['autonomous-execution'],
    applicableRules: ['evidence-before-assertion'],
    executionRules: ['verification-before-completion', 'orchestrator-first'],
  },
  explore: {
    name: 'explore',
    phrase: 'explore / explain / map / understand',
    patterns: [
      { keyword: /\bexplore\b/, weight: 3 },
      { keyword: /\bexplain\b/, weight: 3 },
      { keyword: /\bhow\b/, weight: 1 },
      { keyword: /\bmap\b/, weight: 2 },
      { keyword: /\bunderstand\b/, weight: 1 },
      { keyword: /\barchitecture\b/, weight: 2 },
      { keyword: /\bcodebase\b/, weight: 1 },
      { keyword: /\bwhere is\b/, weight: 2 },
      { keyword: /\bhow does (the|this)\b/, weight: 2 },
      { keyword: /\btour of\b/, weight: 2 },
      // Plan 31 A2 — stickiness keyword patterns
      { keyword: /\bwhat (does|should|is|are)\b/, weight: 2 },
      { keyword: /\bhow do (i|we|you)\b/, weight: 2 },
    ],
    defaultAgent: 'code-explorer',
    defaultSkills: ['codebase-mapping', 'project-exploration'],
    applicableRules: ['evidence-before-assertion'],
  },
  review: {
    name: 'review',
    phrase: 'review / audit / quality',
    patterns: [
      { keyword: /\breview\b/, weight: 3 },
      { keyword: /\baudit\b/, weight: 2 },
      { keyword: /\bcode quality\b/, weight: 2 },
      { keyword: /\bpr\b/, weight: 1 },
      { keyword: /\bfeedback on\b/, weight: 2 },
      { keyword: /\blook at (my|this) (pr|code)\b/, weight: 3 },
      { keyword: /\bquality of\b/, weight: 1 },
    ],
    defaultAgent: 'code-reviewer',
    defaultSkills: ['code-review', 'security-auditing'],
    applicableRules: [
      'evidence-before-assertion',
      'rationalization-prevention',
    ],
    executionRules: ['orchestrator-first'],
  },
  debug: {
    name: 'debug',
    phrase: 'debug / fix / bug / broken / failing',
    patterns: [
      { keyword: /\bdebug\b/, weight: 3 },
      { keyword: /\bfix\b/, weight: 1 },
      { keyword: /\bbug\b/, weight: 2 },
      { keyword: /\bbroken\b/, weight: 2 },
      { keyword: /\berror\b/, weight: 1 },
      { keyword: /\bfailing\b/, weight: 2 },
      { keyword: /\bflaky\b/, weight: 2 },
      { keyword: /\bintermittent\b/, weight: 2 },
      { keyword: /\bbug in\b/, weight: 2 },
      { keyword: /\bnot working\b/, weight: 2 },
      { keyword: /\bdoesn'?t work\b/, weight: 2 },
      { keyword: /\berrors? (when|on)\b/, weight: 2 },
      // Plan 31 A2 — stickiness keyword patterns
      { keyword: /\b(this|that|it) (is|seems|looks) broken\b/, weight: 2 },
    ],
    negativePatterns: [
      { keyword: /\bnot a bug\b/, weight: 10 },
      { keyword: /\bworking as intended\b/, weight: 10 },
    ],
    defaultAgent: 'ultra-worker',
    defaultSkills: ['debugging'],
    applicableRules: [
      'rationalization-prevention',
      'evidence-before-assertion',
    ],
    executionRules: ['verification-before-completion', 'orchestrator-first'],
  },
  plan: {
    name: 'plan',
    phrase: 'plan / break down / decompose / design',
    patterns: [
      { keyword: /\bplan\b/, weight: 3 },
      { keyword: /\bbreak down\b/, weight: 2 },
      { keyword: /\bdecompose\b/, weight: 2 },
      { keyword: /\barchitect\b/, weight: 2 },
      { keyword: /\bdesign\b/, weight: 1 },
      { keyword: /\broadmap\b/, weight: 2 },
      { keyword: /\bmilestones?\b/, weight: 2 },
      { keyword: /\bsubtasks?\b/, weight: 2 },
    ],
    defaultAgent: 'code-architect',
    defaultSkills: ['plan-writing', 'brainstorming'],
    applicableRules: ['one-percent-rule'],
    executionRules: ['orchestrator-first'],
  },
  research: {
    name: 'research',
    phrase: 'research / investigate / analyze / compare',
    patterns: [
      { keyword: /\bresearch\b/, weight: 3 },
      { keyword: /\binvestigate\b/, weight: 2 },
      { keyword: /\banalyze\b/, weight: 2 },
      { keyword: /\bcompare\b/, weight: 1 },
      { keyword: /\boptions for\b/, weight: 2 },
      { keyword: /\balternatives to\b/, weight: 2 },
      { keyword: /\bstate of the art\b/, weight: 2 },
    ],
    defaultAgent: 'researcher',
    defaultSkills: ['deep-diving'],
    applicableRules: ['evidence-before-assertion'],
    executionRules: ['orchestrator-first'],
  },
  test: {
    name: 'test',
    phrase: 'test / tdd / coverage',
    patterns: [
      { keyword: /\btests?\b/, weight: 2 },
      { keyword: /\btdd\b/, weight: 3 },
      { keyword: /\bcoverage\b/, weight: 2 },
      { keyword: /\bspec\b/, weight: 2 },
      { keyword: /\bwrite tests? for\b/, weight: 3 },
      { keyword: /\bbroken test\b/, weight: 3 },
      { keyword: /\bregression test\b/, weight: 3 },
    ],
    negativePatterns: [
      { keyword: /\bnot a test\b/, weight: 10 },
      { keyword: /\bskip (the )?tests?\b/, weight: 10 },
      { keyword: /\bwithout tests?\b/, weight: 10 },
    ],
    defaultAgent: 'ultra-worker',
    defaultSkills: ['test-driven-development'],
    applicableRules: [],
    executionRules: ['verification-before-completion', 'orchestrator-first'],
    workflowRules: ['tdd-iron-law'],
  },
  mcp: {
    name: 'mcp',
    phrase: 'mcp / model context protocol / tool server',
    patterns: [
      { keyword: /\bmcp\b/, weight: 3 },
      { keyword: /\bmodel context protocol\b/, weight: 3 },
      { keyword: /\btool server\b/, weight: 2 },
      { keyword: /\bsse endpoint\b/, weight: 2 },
      { keyword: /\bstdio mcp\b/, weight: 2 },
    ],
    defaultAgent: 'mcp-builder',
    defaultSkills: ['mcp-construction'],
    applicableRules: [],
    executionRules: ['verification-before-completion', 'orchestrator-first'],
  },
  document: {
    name: 'document',
    phrase: 'document / docs / readme',
    patterns: [
      { keyword: /\bdocument\b/, weight: 2 },
      { keyword: /\bdocs\b/, weight: 2 },
      { keyword: /\bdocumentation\b/, weight: 3 },
      { keyword: /\breadme\b/, weight: 2 },
      { keyword: /\bwrite up\b/, weight: 2 },
      { keyword: /\bexplain in docs\b/, weight: 3 },
      { keyword: /\bdocument the\b/, weight: 2 },
    ],
    defaultAgent: 'ultra-worker',
    defaultSkills: ['doc-writing'],
    applicableRules: ['evidence-before-assertion'],
  },
  refactor: {
    name: 'refactor',
    phrase: 'refactor / simplify / clean up',
    patterns: [
      { keyword: /\brefactor\b/, weight: 3 },
      { keyword: /\bsimplify\b/, weight: 2 },
      { keyword: /\bclean up\b/, weight: 2 },
      { keyword: /\brestructure\b/, weight: 2 },
      { keyword: /\bconsolidate\b/, weight: 2 },
      { keyword: /\bextract\b/, weight: 1 },
      { keyword: /\brename\b/, weight: 1 },
      { keyword: /\breorganize\b/, weight: 2 },
      // Plan 31 A2 — stickiness keyword patterns
      { keyword: /\bspeed (it|this) up\b/, weight: 2 },
    ],
    negativePatterns: [
      { keyword: /\bdon'?t refactor\b/, weight: 10 },
      { keyword: /\bno refactor\b/, weight: 10 },
    ],
    defaultAgent: 'code-simplifier',
    defaultSkills: ['slop-removal'],
    applicableRules: ['one-percent-rule'],
    executionRules: ['verification-before-completion', 'orchestrator-first'],
  },
  'review-respond': {
    name: 'review-respond',
    phrase: 'respond to review / address feedback / apply feedback',
    patterns: [
      { keyword: /\brespond to (the )?review\b/, weight: 5 },
      { keyword: /\baddress (the )?review\b/, weight: 5 },
      { keyword: /\bapply (the )?feedback\b/, weight: 4 },
      { keyword: /\bincorporate (the )?feedback\b/, weight: 4 },
      { keyword: /\bfix the (nits|review)\b/, weight: 4 },
      { keyword: /\bpr feedback\b/, weight: 4 },
      { keyword: /\breview (comments?|notes)\b/, weight: 4 },
      { keyword: /\bresolve comments?\b/, weight: 3 },
    ],
    defaultAgent: 'ultra-worker',
    defaultSkills: ['review-response', 'code-review'],
    applicableRules: [
      'rationalization-prevention',
      'evidence-before-assertion',
    ],
    executionRules: ['orchestrator-first'],
  },
  install: {
    name: 'install',
    phrase: 'install / bootstrap / set up anvil',
    patterns: [
      { keyword: /\binstall\b/, weight: 3 },
      { keyword: /\bbootstrap\b/, weight: 2 },
      { keyword: /\bset up anvil\b/, weight: 3 },
      { keyword: /\binit anvil\b/, weight: 3 },
      { keyword: /\binstall anvil\b/, weight: 3 },
      { keyword: /\buninstall\b/, weight: 2 },
      { keyword: /\bdoctor\b/, weight: 1 },
    ],
    defaultAgent: 'ultra-worker',
    defaultSkills: [],
    applicableRules: [],
    executionRules: ['verification-before-completion'],
  },
}

export const INTENT_NAMES: IntentName[] = Object.keys(
  INTENT_DEFINITIONS,
) as IntentName[]
