/**
 * ANV-0138 — `surfaces-audit/dimension-drift` doctor row.
 *
 * Runs the five-dimension surfaces audit and emits a single warn-class row
 * summarising the total flagged-row count per dimension. Silent (pass) when
 * every surface is clean.
 *
 * The row is intentionally warn-only — drift is a signal to file remediation
 * tickets, not a release blocker. The full per-row matrix is generated by
 * the `scripts/audit/surfaces-audit.ts` script and committed under
 * `.anvil/audits/_v0.14.0-surfaces-audit.md`.
 *
 * Read-only: this check imports the pure core library and walks files; it
 * never writes.
 */

import { existsSync } from 'node:fs'
import { join } from 'node:path'

import { auditTree } from '../../../core/audit/surfaces.js'

// Local mirror of the Check interface from doctor.ts.
interface Check {
  name: string
  status: 'pass' | 'warn' | 'fail' | 'skip'
  detail: string
  expectedAbsence?: boolean
  alwaysVisible?: boolean
}

const ROW_NAME = 'surfaces-audit/dimension-drift'

/**
 * Pushes the surfaces-audit drift row. Status:
 *   - pass  — every surface clean on every applicable dimension.
 *   - warn  — at least one surface flagged on at least one dimension.
 *   - skip  — `skills/` directory missing (not in an Anvil tree).
 */
export function pushSurfacesAuditDriftCheck(
  checks: Check[],
  cwd: string,
): void {
  // Cheap presence check — if the canonical skills/ tree is missing, the
  // audit is meaningless. Don't crash; emit a skip.
  if (!existsSync(join(cwd, 'skills'))) {
    checks.push({
      name: ROW_NAME,
      status: 'skip',
      detail: 'skills/ directory not present — not an Anvil source tree',
      expectedAbsence: true,
    })
    return
  }

  let matrix: ReturnType<typeof auditTree>
  try {
    matrix = auditTree({ cwd })
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    checks.push({
      name: ROW_NAME,
      status: 'skip',
      detail: `audit failed to run: ${msg}`,
    })
    return
  }

  const f = matrix.flagged_per_dimension
  const total =
    f.templates + f.model + f.effort + f.tools + f.invocable + f.oc_visible

  if (total === 0) {
    checks.push({
      name: ROW_NAME,
      status: 'pass',
      detail: `all ${matrix.rows.length} surface(s) clean on 5 dimensions`,
      expectedAbsence: true,
    })
    return
  }

  // Compact one-liner: list non-zero dimensions only.
  const parts: string[] = []
  if (f.templates) parts.push(`templates=${f.templates}`)
  if (f.model) parts.push(`model=${f.model}`)
  if (f.effort) parts.push(`effort=${f.effort}`)
  if (f.tools) parts.push(`tools=${f.tools}`)
  if (f.invocable) parts.push(`invocable=${f.invocable}`)
  if (f.oc_visible) parts.push(`oc_visible=${f.oc_visible}`)

  checks.push({
    name: ROW_NAME,
    status: 'warn',
    detail: `${total} dimension flag(s) across ${matrix.rows.length} surfaces — ${parts.join(', ')} (see .anvil/audits/_v0.14.0-surfaces-audit.md)`,
  })
}
