#!/usr/bin/env bun
/**
 * ANV-0067 — Routing-rules generator.
 *
 * Reads INTENT_DEFINITIONS from src/intent/intents.ts and regenerates
 * src/core/routing-rules-content.ts so the two cannot drift.
 *
 * The generated file is committed; CI regenerates and diffs to catch drift.
 * The doctor row "routing-rules sync" also detects hand-edits to the
 * generated file.
 *
 * Usage:
 *   bun run scripts/generate-routing-rules.ts          # write file
 *   bun run scripts/generate-routing-rules.ts --check  # exit 1 if diff detected
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { INTENT_DEFINITIONS, INTENT_NAMES } from '../src/intent/intents.js'

const here = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(here, '..')
const OUT = resolve(ROOT, 'src', 'core', 'routing-rules-content.ts')

const CHECK_MODE = process.argv.includes('--check')

// ---------------------------------------------------------------------------
// Build the ROUTING_INTENT_TABLE entries from INTENT_DEFINITIONS.
// Intents with no defaultSkills (e.g. "install") are included but emit an
// empty skills array — the routing prose handles that gracefully.
// ---------------------------------------------------------------------------

function buildTableSource(): string {
  const entries = INTENT_NAMES.map((name) => {
    const def = INTENT_DEFINITIONS[name]
    const q = (s: string) => `'${s.replaceAll("'", "\\'")}'`
    const skillsLiteral =
      def.defaultSkills.length === 0
        ? '[]'
        : `[${def.defaultSkills.map(q).join(', ')}]`
    return (
      `  {\n` +
      `    intent: ${q(def.name)},\n` +
      `    phrase: ${q(def.phrase)},\n` +
      `    agent: ${q(def.defaultAgent)},\n` +
      `    skills: ${skillsLiteral},\n` +
      `  }`
    )
  })
  return entries.join(',\n')
}

// ---------------------------------------------------------------------------
// Emit the full routing-rules-content.ts source
// ---------------------------------------------------------------------------

function buildFileContent(): string {
  const tableEntries = buildTableSource()
  return `/**
 * Canonical content for \`.claude/rules/anvil-routing.md\` (Plan 31 B5)
 * and the \`<!-- anvil-routing -->\` block in \`AGENTS.md\` (Plan 32 F2).
 *
 * Placed in src/core/ so both the installer (Layer 7) and the doctor command
 * (Layer 4) can import the same constants for idempotency checks without
 * duplicating the string. Layer 0 — no I/O, no side-effects.
 *
 * ANV-0067: this file is GENERATED by \`scripts/generate-routing-rules.ts\`.
 * Do not edit by hand — edit \`src/intent/intents.ts\` instead and regenerate:
 *   bun run generate:routing-rules
 *
 * A doctor row ("routing-rules sync") detects hand-edits and fails accordingly.
 */

/**
 * Structured routing-rules table — generated from \`src/intent/intents.ts\`.
 *
 * \`intent\` matches an \`IntentName\` from \`src/intent/intents.ts\` (verified by
 * tests). \`phrase\` is the user-facing keyword list rendered verbatim into
 * the prose. \`agent\` is the agent slug (must exist under \`agents/\`).
 * \`skills\` is the ordered skill list (each must exist under \`skills/\`).
 *
 * Skill slugs MUST be activity-nouns (e.g. \`code-review\`, \`planning\`).
 * Agent slugs MUST end in an approved doer-suffix (e.g. \`code-reviewer\`).
 * The two are not interchangeable — see \`CLAUDE.md\` "Skills vs Agents".
 */
export interface RoutingIntentEntry {
  readonly intent: string
  readonly phrase: string
  readonly agent: string
  readonly skills: readonly string[]
}

export const ROUTING_INTENT_TABLE: readonly RoutingIntentEntry[] = [
${tableEntries},
] as const

/**
 * Render one intent line in canonical form, e.g.:
 *   "- plan / break down → \`code-architect\` agent + \`planning\` / \`plan-writing\` skills"
 *
 * The format is stable: \`phrase → \\\`agent\\\` agent + \\\`s1\\\` / \\\`s2\\\` skill(s)\`.
 */
function renderIntentLine(entry: RoutingIntentEntry): string {
  if (entry.skills.length === 0) {
    return \`- \${entry.phrase} → \\\`\${entry.agent}\\\` agent\`
  }
  const skillList = entry.skills.map((s) => \`\\\`\${s}\\\`\`).join(' / ')
  const skillNoun = entry.skills.length === 1 ? 'skill' : 'skills'
  return \`- \${entry.phrase} → \\\`\${entry.agent}\\\` agent + \${skillList} \${skillNoun}\`
}

const INTENT_LINES = ROUTING_INTENT_TABLE.map(renderIntentLine).join('\\n')

/**
 * Canonical content for \`.claude/rules/anvil-routing.md\`.
 * Generated from \`ROUTING_INTENT_TABLE\`.
 */
export const ANVIL_ROUTING_RULES_CONTENT = \`# Anvil routing — standing instructions

When the user's prompt matches one of these intents, prefer the Anvil agent/skill over inline work or built-in agents:

\${INTENT_LINES}

Override with explicit \\\`/skill\\\` or \\\`@agent\\\` user invocation. Never silently bypass when a directive fires at confidence ≥0.65.
\`

/**
 * Canonical block content for the \`<!-- anvil-routing -->\` marker section
 * written into \`AGENTS.md\` at repo root for OpenCode (Plan 32 F2).
 *
 * OpenCode natively loads \`AGENTS.md\` at session start (≥v1.1.37), making
 * it the confirmed standing-instructions surface. The content mirrors the
 * CC version but uses tool-agnostic phrasing ("invocation" instead of
 * "user invocation").
 *
 * The installer wraps this between HTML comment markers so it can be updated
 * in place without clobbering other AGENTS.md content.
 *
 * See ADR: .anvil/_archive/docs-anvil/specs/2026-04-26-opencode-standing-instructions.md
 */
export const ANVIL_OC_ROUTING_CONTENT = \`## Anvil routing — standing instructions

When the user's prompt matches one of these intents, prefer the Anvil agent/skill over inline work or built-in agents:

\${INTENT_LINES}

Override with explicit \\\`/skill\\\` or \\\`@agent\\\` invocation. Never silently bypass when a directive fires at confidence ≥0.65.
\`

/**
 * The HTML comment markers that delimit the Anvil routing block in AGENTS.md.
 * Must remain stable across versions — changing them breaks idempotency checks
 * against files written by older installer versions.
 */
export const OC_ROUTING_MARKER_OPEN = '<!-- anvil-routing -->'
export const OC_ROUTING_MARKER_CLOSE = '<!-- /anvil-routing -->'

/**
 * Extract every slug referenced in a routing-rules document.
 *
 * Returns the set of backtick-quoted identifiers (skill or agent slugs)
 * appearing in the prose. Used by tests to assert that every referenced
 * slug exists on disk — guards against ANV-0017 W-004 style hallucinations
 * where prose drifts from the registries.
 */
export function extractReferencedSlugs(content: string): string[] {
  const out: string[] = []
  const re = /\`([a-z][a-z0-9-]*)\`/g
  let match: RegExpExecArray | null
  // biome-ignore lint/suspicious/noAssignInExpressions: idiomatic regex iteration
  while ((match = re.exec(content)) !== null) {
    if (match[1]) out.push(match[1])
  }
  return out
}

/**
 * Validate a routing-rules document against the supplied skill/agent slug
 * sets. Returns the list of slugs referenced in \`content\` that are absent
 * from BOTH sets. An empty array means the prose is registry-clean.
 *
 * \`knownSkills\` should hold every skill slug from the on-disk registry
 * (e.g. directory walk under \`skills/\`). \`knownAgents\` likewise for
 * \`agents/\`. The validator does not enforce skill-vs-agent classification —
 * it only checks existence. The classification check lives in the
 * intent-metadata cross-check test.
 */
export function findUnknownSlugs(
  content: string,
  knownSkills: ReadonlySet<string>,
  knownAgents: ReadonlySet<string>,
): string[] {
  const referenced = extractReferencedSlugs(content)
  return referenced.filter(
    (slug) => !knownSkills.has(slug) && !knownAgents.has(slug),
  )
}
`
}

// ---------------------------------------------------------------------------
// Write or check
// ---------------------------------------------------------------------------

const generated = buildFileContent()

if (CHECK_MODE) {
  if (!existsSync(OUT)) {
    console.error(
      `ERROR: ${OUT} does not exist — run generate:routing-rules first`,
    )
    process.exit(1)
  }
  const committed = readFileSync(OUT, 'utf-8')
  if (committed !== generated) {
    console.error(
      'ERROR: routing-rules-content.ts is out of sync with intents.ts\n' +
        'Run `bun run generate:routing-rules` and commit the result.',
    )
    process.exit(1)
  }
  console.log('routing-rules-content.ts is in sync with intents.ts')
} else {
  writeFileSync(OUT, generated, 'utf-8')
  console.log(`wrote ${OUT}`)
}
